/*
 * CloudFabrix RDA Platform API
 * CloudFabrix RDA Platform API
 *
 * The version of the OpenAPI document: 3.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatasetAddModel
 */
public class DatasetAddModelTest {
    private final DatasetAddModel model = new DatasetAddModel();

    /**
     * Model tests for DatasetAddModel
     */
    @Test
    public void testDatasetAddModel() {
        // TODO: test DatasetAddModel
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'folder'
     */
    @Test
    public void folderTest() {
        // TODO: test folder
    }

    /**
     * Test the property 'schemaName'
     */
    @Test
    public void schemaNameTest() {
        // TODO: test schemaName
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

}
