/*
 * CloudFabrix RDA Platform API
 * CloudFabrix RDA Platform API
 *
 * The version of the OpenAPI document: 3.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TableReportResponse
 */
public class TableReportResponseTest {
    private final TableReportResponse model = new TableReportResponse();

    /**
     * Model tests for TableReportResponse
     */
    @Test
    public void testTableReportResponse() {
        // TODO: test TableReportResponse
    }

    /**
     * Test the property 'lastSortResults'
     */
    @Test
    public void lastSortResultsTest() {
        // TODO: test lastSortResults
    }

    /**
     * Test the property 'reportMetaData'
     */
    @Test
    public void reportMetaDataTest() {
        // TODO: test reportMetaData
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

    /**
     * Test the property 'numItems'
     */
    @Test
    public void numItemsTest() {
        // TODO: test numItems
    }

    /**
     * Test the property 'isFirst'
     */
    @Test
    public void isFirstTest() {
        // TODO: test isFirst
    }

    /**
     * Test the property 'isLast'
     */
    @Test
    public void isLastTest() {
        // TODO: test isLast
    }

}
