/*
 * CloudFabrix RDA Platform API
 * CloudFabrix RDA Platform API
 *
 * The version of the OpenAPI document: 3.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserDetails
 */
public class UserDetailsTest {
    private final UserDetails model = new UserDetails();

    /**
     * Model tests for UserDetails
     */
    @Test
    public void testUserDetails() {
        // TODO: test UserDetails
    }

    /**
     * Test the property 'authenticated'
     */
    @Test
    public void authenticatedTest() {
        // TODO: test authenticated
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isAuthenticated'
     */
    @Test
    public void isAuthenticatedTest() {
        // TODO: test isAuthenticated
    }

    /**
     * Test the property 'isWorkspaceadmin'
     */
    @Test
    public void isWorkspaceadminTest() {
        // TODO: test isWorkspaceadmin
    }

    /**
     * Test the property 'isWorkspacecreator'
     */
    @Test
    public void isWorkspacecreatorTest() {
        // TODO: test isWorkspacecreator
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'lastname'
     */
    @Test
    public void lastnameTest() {
        // TODO: test lastname
    }

    /**
     * Test the property 'loginTime'
     */
    @Test
    public void loginTimeTest() {
        // TODO: test loginTime
    }

    /**
     * Test the property 'rdacAuthToken'
     */
    @Test
    public void rdacAuthTokenTest() {
        // TODO: test rdacAuthToken
    }

    /**
     * Test the property 'remoteUser'
     */
    @Test
    public void remoteUserTest() {
        // TODO: test remoteUser
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'tenantid'
     */
    @Test
    public void tenantidTest() {
        // TODO: test tenantid
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'workspace'
     */
    @Test
    public void workspaceTest() {
        // TODO: test workspace
    }

    /**
     * Test the property 'workspaceid'
     */
    @Test
    public void workspaceidTest() {
        // TODO: test workspaceid
    }

}
